# Characteristics of electromagnetic fields and radiation

## Clean waves versus waves used for communication

### Clean waves

### Pulses

When talking about *pulsed* waves, how can 
we try to understand what is meant, as concretely as possible?

Presman [@presmanElectromagneticFieldsLife1970a, pp. 120-121] provides a description, from which we can infer what *pulses* really are (my emphasis):

> [...] [a] series of experiments in which different regions of the body were exposed to more intense radiation – **pulses of continuous waves** (700-1200 mW/cm² per pulse) **or a series of short pulses** (1 µsec long, 700 pulses/sec, mean power in series 350-380 mW/cm²), **the duration of the pulses and series being 0.1 sec and the repetition rate two per second.**



So pulses has several components, and can happen with both continuous waves (on/off) and a series of smaller pulses within each pulse. 

The first component is the amount of time the pulse is on, here 0.1 seconds.

Think of the continuous wave pulse as a burst of radiation, that turns on for that specific amount of time.

The second component is the repition rate, here two times per second. One can infer from that the time the wave is off, here it must be 0.4 seconds, since there are only two 0.1 second pulses per second, i.e. the pulse is off for a total of 0.8 seconds, per second. 

In addition, if the radition is not a continuous wave, it can instead be seen as *pulses within pulses*, or *outer* and *inner* pulses, in such a way that for each two  0.1 second burst, per second there are actually 
700 smaller 1 µsec long pulses where the radiaion is turned on/off. An *inner* pulses. Since there are 700 pulses per second, but the pulse is only 0.1 second each time, then there are 70 pulses each time the *outer* pulse is on, so 140 pulses in total per second.




### Polarization



## Natural electromagnetism

### Space and the sun

*Coronal mass ejection (CME)*: 
Ejection of plasma mass from the sun. One often talks about flares, and flares 
of different strength, e.g. X1 to X100. The Carrington event (1859) is said to
have been between X45 or  X80 flare (ADD REFERENCE). One also talk about the 
KP-index – the geomagnetic storm index, with values like typically Kp5-Kp9.


*Cosmic microwave background radiation* (CMB(R)): (LOOK UP AND IMPROVE TERMINOLOGY
AND ABREVIATION, NOT SURE IF THIS IS USED OR COMMONLY USED) 