# Preface {.unnumbered}

::: {.callout-tip icon=false}
##
*The best book for scientific ideas, including generating new ideas and bringing ideas to life – within the field of biological and health effects of electromagnetic fields (EMF).*
:::

This is a collection of theories and hypotheses related to the study of biological and health effects of non-ionizing radiation.

The book is an open science project started in 2024 and is work in progress. A final edition may take years to complete. Scientists and authors familiar with the topic can contribute and will be credited for any contribution. If you want to contribute, you can simply submit additions and revisions at the book's [GitHub repository](https://github.com/cortexR/emf-research-book/). Currently, I serve as the editor, but that may be changed if more experienced authors decide to contribute.

The book at this page will remain free. The book is licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en). Potentially, 
additional paperback, hard copy or e-book editions can be made available for 
sale at a future point in time.

The aim of the book is to be a comprehensive list of the theories and hypotheses related to non-ionizing radiation that can be used for researchers and others who want to familiar themselves with the topic; look up potential frameworks to interpret findings; or explore research gaps and possible new research questions and methods.

The aim is not to discuss specific research findings, but rather to provide a scope
of theories. However, relevant scientific references for each theory should be included. 
But to support the progress of the development of this book, such lists may most often not be exhaustive, meaning that a theory may be included with one reference initially that is not necessarily the most updated and correct reference. 

It is also not the aim that theories or hypotheses included should have 
been proven to be correct (or scientifically speaking, not haven been falsified).
Theories that are speculative, or even wrong, may also be included, 
and the reader should be aware this. The reason for this is that ideas that have 
not yet been researched may have extra value in that they may point to 
research gaps, and theories that have proven wrong may prohibit other 
researchers to waste their efforst following that same path. 


