# Specific diseases (draft)

## Cardiovascular disease

### Blood pressure

Cell phone calls, and thus radiofrequency radiation, may be related to the development of high *blood-pressure* (hypertension) , according to a large study using data from the UK Biobank [@yeMobilePhoneCalls2023a]. Radiation exposure can be assumed to be strongly affected by cell phone usage. Confounding factors and other explanatory models can always exist. Mecanistic models for how a blood pressure increase can happen due to radiofrequency radiation, is a topic for future studies, – and such studies will increase the confidence in the findings from epidemiological studies on cell phone usage or similar exposure, and blood pressure.

## Cancer

One of the earliest finding of cancer (malignant tumors) fom RF exposure was found in rats in 1984 [@microwavenewsMicrowavesPromoteCancer1984] The finding came after exposure to low level pulsed 2450 MHz radiation, in the first long-term study on microwave exposure in the United States, funded by the U.S. Air Force in a \$5 million (1984 value) dollar study. Notably, it took eight years from the findings were first presented at a conference until they were published in a scientific journal [@microwavenewsUpdatesGuyStudy1993;@chouLongtermLowlevelMicrowave1992].
